### ISSUE TITLE
Money not added up when perform 2 actions at once.

### ISSUE THREAD

**Issue by FaceWithDark** [NekoOfficial/Neko.cf#1]
![image](https://github.com/NekoOfficial/Neko.cf/assets/114546939/82489fdf-6f01-4c2a-9f89-6a0713ac91f6)

- According to the image, I was supposed to have a total of **94¥** in my Neko's bank account. 

> [!NOTE]
> It is an add-up from: 60 (initial money) + 9 (toss win) + 25 (working)

- When I performed a re-toss, which shows on the second last sentence / command from the image, it didn't recognise my money from the working command.

> [!WARNING]
> I want my money back.

**Comment by buttermiilk** [comment]
noted - will be fixed in a while

**Comment by buttermiilk** [comment]
should be fixed - test it out and lmk if you're still facing this issue

**Comment by FaceWithDark** [comment]
Maybe tmr. It worked normally for now.
